### ISSUE TITLE
shortReads_assembly.wdl should output bbcms error corrected data

### ISSUE THREAD

**Issue by aclum** [microbiomedata/metaAssembly#18]
The output of short read assembly should be included in the final output.  The fastq headers do not need to be renamed but this should be included in the final workflow output and the workflow automation should make a data object for it.
This ticket is to get the WDL updated so that these bbcms task output files are get passed as outputs to the workflow, not just as outputs of the bbcms task.

            File out = filename_outfile
            File out1 = if paired then filename_outfile1 else filename_outfile
            File out2 = if paired then filename_outfile2 else filename_outfile

**Comment by vlilanl** [comment]
Shane and I tested this last week, and we had a successful run. @aclum do you want to look over it?

**Comment by aclum** [comment]
@vlilanl  where is the run and would you be able to do a pull request?

**Comment by vlilanl** [comment]
This should be the run id: 8022a0d2-6443-457b-996f-de13b28cf337. I can try and do a pull request.

**Comment by vlilanl** [comment]
New ticket for nmdc_automation: https://github.com/microbiomedata/nmdc_automation/issues/189
