### ISSUE TITLE
Workflows - Test large data sets for workflows (metaAssembly)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/metaAssembly#2]
create a large test data set with expected outcome if workflow run is successful

link test results to this issue

**Comment by ssarrafan** [comment]
From: Setareh Sarrafan <ssarrafan@lbl.gov>
Date: Mon, May 3, 2021 at 9:12 AM
Subject: Re: [EXTERNAL] GitHub issues
To: Hu, Bin <bhu@lanl.gov>
Cc: Kjiersten Fagnan <kmfagnan@lbl.gov>


Hi Bin,

Is it ok if I move the open workflow related GitHub issues to the May sprint?  If there are any that you don't plan to work on in May let me know, or if there are ones that you made some progress and would like to close let me know, otherwise I was planning to move the following to May sprint:
 

Thanks, Setareh

On Fri, Apr 23, 2021 at 1:03 PM Setareh Sarrafan <ssarrafan@lbl.gov> wrote:
Thanks for the update Bin.  If you'd like Michal to get a GitHub account let me know.  For now I'll leave the GitHub issues as they are and we'll see how it goes next week. 
Best, Set

**Comment by hubin-keio** [comment]
Will be tested at SDSC once the system (Cromwell etc.) is set up. Likely to get started near the last week of the Sprint.

**Comment by ssarrafan** [comment]
Closing per Bin's comment that this is done.
