### ISSUE TITLE
stats file is not being propagated to the final outputs -short reads workflow

### ISSUE THREAD

**Issue by aclum** [microbiomedata/metaAssembly#21]
From the short reads workflow wdl shortReads_assembly.wdl we need outasmstats, this has the assembly stats, that file needs get propagated to be part of the output of jgi_metaAssembly in jgi_assembly.wdl.

The name of that output also needs to match what is in the workflow config file (https://github.com/microbiomedata/nmdc_automation/blob/main/configs/import.yaml) currently named 'stats' so either name the file that or you'll need a pull request on nmdc_automation to the new name.

cc @chienchi @mbthornton-lbl

**Comment by vlilanl** [comment]
The workflow currently has the asmstats as an output for the main workflow:
> https://github.com/microbiomedata/metaAssembly/blob/58c8ad7868c74157bcfdd7022421aadb9d34f646/jgi_assembly.wdl#L101
>
Do you want me to rename this to stats as well?

**Comment by aclum** [comment]
That is not the right file, we need finish_asm.outasmstats

**Comment by vlilanl** [comment]
Is it this file?

> https://github.com/microbiomedata/metaAssembly/blob/58c8ad7868c74157bcfdd7022421aadb9d34f646/shortReads_assembly.wdl#L106

> https://github.com/microbiomedata/metaAssembly/blob/58c8ad7868c74157bcfdd7022421aadb9d34f646/shortReads_assembly.wdl#L240

**Comment by aclum** [comment]
yes

**Comment by ssarrafan** [comment]
@vlilanl will this be done by tomorrow?

**Comment by vlilanl** [comment]
Perlmutter is down so I cannot test anything at the moment, I do hope to close these tickets tomorrow as long as testing goes smoothly.

**Comment by ssarrafan** [comment]
Moving to next sprint for Vivian

**Comment by vlilanl** [comment]
Successful Short reads test: 90023

JAWs queue has been taking a while so long reads is still being tested
