### ISSUE TITLE
json stats file creation for the long read workflow

### ISSUE THREAD

**Issue by aclum** [microbiomedata/metaAssembly#22]
I can't tell if this is being made or not, if it is list what output variable name is being used in jgi_assembly.wdl to specify it.

**Comment by vlilanl** [comment]
Long Reads has these two stats files. Do you know which one is needed for automation and does it need to be named stats instead of lr_stats?
> https://github.com/microbiomedata/metaAssembly/blob/58c8ad7868c74157bcfdd7022421aadb9d34f646/jgi_assembly.wdl#L89-L90

**Comment by aclum** [comment]
the finish step for long reads is missing the conversion to json that is happening in the short read workflow. 
https://github.com/microbiomedata/metaAssembly/blob/58c8ad7868c74157bcfdd7022421aadb9d34f646/shortReads_assembly.wdl#L230
