### ISSUE TITLE
Generate SVG version of diagram and update `index.rst` to reference it instead of PNG version

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/metaAssembly#28]
When I use Sphinx to generate the HTML documentation for this workflow (from the files in the `docs` directory), the diagram gets displayed at proportions different from its native proportions, resulting in distortion. This is shown below.

![image](https://github.com/user-attachments/assets/b282af03-6eb9-463c-9201-537d8b9db244)

That can be resolved by using an SVG image instead.

---

Hi @kaijli, I'm assigning this ticket to you because you are the person I've talked to most about the image files in the workflow repos. I don't know whether you are familiar with the image file in this particular repo, though. Do you happen to have a way to generate this one in SVG format, as you have done in some of the other repos recently? You can reassign this ticket (including back to me) in case you don't think it's a good fit for you (I wasn't sure).

**Comment by kaijli** [comment]
Yes, I had them generated already. Let me know if there's others I'm missing!
