### ISSUE TITLE
Workflows - Test small data sets for workflows (metaAssembly)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/metaAssembly#3]
create a small test data set with expected outcome if workflow run is successful

link test results to this issue

**Comment by hubin-keio** [comment]
please point me the location of two test data sets (one smaller set for quick test and one small realistic data set for thorough test) and the expected outcome from each workflow run in JSON format. Thank you.

**Comment by ssarrafan** [comment]
> please point me the location of two test data sets (one smaller set for quick test and one small realistic data set for thorough test) and the expected outcome from each workflow run in JSON format. Thank you.

@hubin-keio you didn't tag anyone in your comment so I assume you don't have what you need to move forward on this. I'll move this to the May sprint. If you need the location from someone please let me know or tag them in this issue.  Thanks!

**Comment by chienchi** [comment]
commit 99d564f
