### ISSUE TITLE
Change to ID method used in contigs

### ISSUE THREAD

**Issue by scanon** [microbiomedata/metaAssembly#7]
After some discussion, it was decided to adjust how the IDs used in the contigs is generated.  The basic idea is to now generate the activity ID up front and then use that in the contig ID.

@scanon will start a PR to show how this could work.  The plan is to have some step at the beginning of the workflow to generate an ID (method TBD) and then that will be included the output from the workflow.  The scripts that currently generate the activity record will need to be modified to take this ID as a parameter.

**Comment by chienchi** [comment]
sounds good to me.

**Comment by ssarrafan** [comment]
Per Slack message from @scanon moving this issue to the July sprint.

**Comment by ssarrafan** [comment]
@scanon is on vacation and decision on IDs was made while he was gone so I will move this to August so he can close it when he's back.

**Comment by ssarrafan** [comment]
@scanon can this issue be closed?

**Comment by scanon** [comment]
I think so.  It has basically been replaced by having an ID service mint the IDs.  There are workflow changes that have to happen too (but most of those are done now).

**Comment by ssarrafan** [comment]
Closing per Shane's comment.
